### ISSUE TITLE
Request: multiple choices

### ISSUE THREAD

**Issue by haakonstorm** [mattieha/select-list-card#5]
For use with Alexa_Media, and selecting multiple Echo Dot locations for announcing/reading aloud written text on multiple locations.

E.g.
```
[ ] echo livingroom
[x] echo bathroom
[x] echo upstairs
```

calls a script with the selected ones, so what is read is coming from both bathroom and upstairs. 
Please let me know if you need more details. This would be awesome for all alexamedia users!

**Comment by mattieha** [comment]
Thanks for your request!

I've been thinking about this feature myself. I didn't see a direct use case for it, but your use case seems a good one.
Since I don't have then alexa integration: 
- can you show how the content of the scripts would look like
- a link to the Alexa_Media integration

**Comment by mattieha** [comment]
I have multiple selectable items working, however I'm not sure when the service call should be done.

In the current version the service call (`input_select.set_option`) is done directly after a click.
When selecting multiple items this is not desirable as it would trigger the service call multiple times.

I'm thinking of a execute button in the footer or header which triggers the service call...
Any suggestions on this?

**Comment by haakonstorm** [comment]
Hey, thanks for getting back to this issue!

Regarding execute button, being a minimalist I'd suggest adding all needed functionality to each list item.

Then control each of those with flags, and having some sensible defaults.

E.g. a boolean flag `immediate_service_call=FALSE` that defaults to `FALSE`.
When set to TRUE *and* selected, we assemble the magic payload minus items flagged `immediate_service_call` and dispatch to HA.

This way, one of the list items can have a friendly_name be `EXECUTE` or similar.

This presumes your library can [semi-]dynamically populate the list as a result of querying HA for the options, and adding/overriding any that are manually set in your codes config.

When we are on it, there are two related issues/features that will inevitablty show up. If you solve these, a myriad of other Home Assistant users can start using this for a vast range of other uses. 

## Key-Value

The first is to enable `key=value` features for users of the HA UI. 
The user, imagine in this case, is Sophia Denise.
Sophia is the wife of ARM64 assembly language programmer Zlobodan Coderodorovic.
Sophia doesn't like lists that looks like this:

```
media_player.echo_kitchen
media_player.echo_bedroom
media_player.echo_bathroom
media_player.echo_elisabeth
media_player.echo_laboratory
media_player.echo_workshop
media_player.echo_auto
media_player.echo_mini
```

or even worse, a list like this:

```
λ hass-cli -o json state list switch |jq -Mr '.[] | .entity_id'|grep -i sonoff

switch.sonoff_100078a0bc
switch.sonoff_100078782e
switch.sonoff_1000795065
switch.sonoff_1000781892
switch.sonoff_1000792bfa
switch.sonoff_1000792989
switch.sonoff_100078c50a
switch.sonoff_100077e618
switch.sonoff_1000736d0c_1
switch.sonoff_1000736d0c_2
switch.sonoff_1000784cc1
switch.sonoff_100073684b_1
switch.sonoff_100073684b_2
```

She wants a list of `friendly_names`, as populated here:

```
hass-cli -o json raw get /api/states/input_select.alexattsselect | jq -Mr '.attributes | .options | .[]' | xargs -L1 -I  zsh -c "echo -n  '= '; hass-cli -o json raw get /api/states/ | jq -Mr '.attributes|.friendly_name'"
```
<img width="688" alt="Screenshot of iTerm2 (21-07-2020, 21-00-55)" src="https://user-images.githubusercontent.com/193781/88096080-651aa780-cb96-11ea-96c7-0899fa4b5761.png">

Perhaps even removing the `entity_id` altogether and just showing the `friendly_name`.

If HA UI users can choose from a `friendly_name` list, but have the back-end receive the `entity_id` list instead, that would be awesome.

## Pre-sets

Related, when lists are both long *and* they are frequenly used, there will be a need for pre-sets, like in "option A and D" and "option X,Y,Z,A,B,Q".

If those presets can be set up somehow, they can have a `friendly_name` as `Zlobos` and resolve to a list of `entity_id`s.

**Comment by haakonstorm** [comment]
Oh, and `alexa_media` can be found over at [https://github.com/custom-components/alexa_media_player](https://github.com/custom-components/alexa_media_player). 

For dev, If you have a spare `Raspberry` or similar, you can set it up with Amazons software and have it appear as an Amazon Echo inside HA with this component.
